spring:
  datasource:
    url: jdbc:h2:mem:project
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

app:
  security:
    cookie:
      access:
        httpOnly: true
        secure: false
        sameSite: Lax          # можно откуда угодно
        maxAgeSeconds: 900       # 15 минут
      refresh:
        httpOnly: true
        secure: false
        sameSite: Lax
        maxAgeSeconds: 2592000   # 30 дней